name: RedRock Software Production

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      # - run: cd /home/ryan/actions-runner/_work/redrock_software/redrock_software/client && npm ci

      - run: rm -rf /home/ryan/server
        continue-on-error: true

      - run: mv /home/ryan/actions-runner/_work/redrock_software/redrock_software/server /home/ryan/server

      - run: cp /home/ryan/config.js /home/ryan/server/config.js

      - run: cd /home/ryan/server && npm ci

      - run: rm -rf /home/ryan/actions-runner/_work
        # continue-on-error: true

      - run: pm2 delete server
        continue-on-error: true

      - run: pm2 flush

      - run: cd /home/ryan/server && NODE_ENV=PROD pm2 start server.js
